// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xaraphix/Sif/internal/raft (interfaces: RaftMonitor)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	raft "github.com/xaraphix/Sif/internal/raft"
)

// MockRaftMonitor is a mock of RaftMonitor interface.
type MockRaftMonitor struct {
	ctrl     *gomock.Controller
	recorder *MockRaftMonitorMockRecorder
}

// MockRaftMonitorMockRecorder is the mock recorder for MockRaftMonitor.
type MockRaftMonitorMockRecorder struct {
	mock *MockRaftMonitor
}

// NewMockRaftMonitor creates a new mock instance.
func NewMockRaftMonitor(ctrl *gomock.Controller) *MockRaftMonitor {
	mock := &MockRaftMonitor{ctrl: ctrl}
	mock.recorder = &MockRaftMonitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRaftMonitor) EXPECT() *MockRaftMonitorMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockRaftMonitor) Start(arg0 *raft.RaftNode) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", arg0)
}

// Start indicates an expected call of Start.
func (mr *MockRaftMonitorMockRecorder) Start(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRaftMonitor)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockRaftMonitor) Stop(arg0 *raft.RaftNode) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop", arg0)
}

// Stop indicates an expected call of Stop.
func (mr *MockRaftMonitorMockRecorder) Stop(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRaftMonitor)(nil).Stop), arg0)
}
