// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RaftRPCAdapterClient is the client API for RaftRPCAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftRPCAdapterClient interface {
	RequestVoteFromPeer(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
	ReplicateLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	BroadcastMessage(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*BroadcastMessageResponse, error)
}

type raftRPCAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftRPCAdapterClient(cc grpc.ClientConnInterface) RaftRPCAdapterClient {
	return &raftRPCAdapterClient{cc}
}

func (c *raftRPCAdapterClient) RequestVoteFromPeer(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, "/RaftRPCAdapter/RequestVoteFromPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCAdapterClient) ReplicateLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, "/RaftRPCAdapter/ReplicateLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCAdapterClient) BroadcastMessage(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*BroadcastMessageResponse, error) {
	out := new(BroadcastMessageResponse)
	err := c.cc.Invoke(ctx, "/RaftRPCAdapter/BroadcastMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftRPCAdapterServer is the server API for RaftRPCAdapter service.
// All implementations must embed UnimplementedRaftRPCAdapterServer
// for forward compatibility
type RaftRPCAdapterServer interface {
	RequestVoteFromPeer(context.Context, *VoteRequest) (*VoteResponse, error)
	ReplicateLog(context.Context, *LogRequest) (*LogResponse, error)
	BroadcastMessage(context.Context, *structpb.Struct) (*BroadcastMessageResponse, error)
	mustEmbedUnimplementedRaftRPCAdapterServer()
}

// UnimplementedRaftRPCAdapterServer must be embedded to have forward compatible implementations.
type UnimplementedRaftRPCAdapterServer struct {
}

func (UnimplementedRaftRPCAdapterServer) RequestVoteFromPeer(context.Context, *VoteRequest) (*VoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVoteFromPeer not implemented")
}
func (UnimplementedRaftRPCAdapterServer) ReplicateLog(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicateLog not implemented")
}
func (UnimplementedRaftRPCAdapterServer) BroadcastMessage(context.Context, *structpb.Struct) (*BroadcastMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastMessage not implemented")
}
func (UnimplementedRaftRPCAdapterServer) mustEmbedUnimplementedRaftRPCAdapterServer() {}

// UnsafeRaftRPCAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftRPCAdapterServer will
// result in compilation errors.
type UnsafeRaftRPCAdapterServer interface {
	mustEmbedUnimplementedRaftRPCAdapterServer()
}

func RegisterRaftRPCAdapterServer(s grpc.ServiceRegistrar, srv RaftRPCAdapterServer) {
	s.RegisterService(&RaftRPCAdapter_ServiceDesc, srv)
}

func _RaftRPCAdapter_RequestVoteFromPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCAdapterServer).RequestVoteFromPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RaftRPCAdapter/RequestVoteFromPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCAdapterServer).RequestVoteFromPeer(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPCAdapter_ReplicateLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCAdapterServer).ReplicateLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RaftRPCAdapter/ReplicateLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCAdapterServer).ReplicateLog(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPCAdapter_BroadcastMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCAdapterServer).BroadcastMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RaftRPCAdapter/BroadcastMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCAdapterServer).BroadcastMessage(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftRPCAdapter_ServiceDesc is the grpc.ServiceDesc for RaftRPCAdapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftRPCAdapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RaftRPCAdapter",
	HandlerType: (*RaftRPCAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVoteFromPeer",
			Handler:    _RaftRPCAdapter_RequestVoteFromPeer_Handler,
		},
		{
			MethodName: "ReplicateLog",
			Handler:    _RaftRPCAdapter_ReplicateLog_Handler,
		},
		{
			MethodName: "BroadcastMessage",
			Handler:    _RaftRPCAdapter_BroadcastMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/raft/raftadapter/protos/adapter.proto",
}
